apiVersion: v2
appVersion: 4.3.0
description: qBittorrent is a cross-platform free and open-source BitTorrent client
name: qbittorrent
version: 1.2.0
upstream_version: 7.2.1
keywords:
  - qbittorrent
  - torrrent
home: https://github.com/truecharts/truecharts/tree/master/charts/qbittorrent
icon: https://cloud.githubusercontent.com/assets/14862437/23586868/89ef2922-01c4-11e7-869c-52aafcece17f.png
sources:
  - https://hub.docker.com/r/linuxserver/qbittorrent/
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: https://charts.truecharts.org/
    version: 1.2.0
