apiVersion: v2
appVersion: latest
description: Private Windows Activation Server for development and testing
name: kms
version: 1.2.0
keywords:
  - kms
home: https://github.com/truecharts/charts/tree/dev/charts/kms
icon: https://github.com/KMS/KMS/blob/phantom-develop/Logo/512.png?raw=true
sources:
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: https://charts.truecharts.org/
    version: 1.2.0

