apiVersion: v2
appVersion: latest
description: TVheadend - a TV streaming server and digital video recorder
name: tvheadend
version: 1.2.0
upstream_version: 1.1.2
keywords:
  - tv
  - streaming
  - dvb
home: https://github.com/truecharts/truecharts/tree/master/charts/tvheadend
icon: https://avatars.githubusercontent.com/u/1908588?s=200&v=4
sources:
  - https://github.com/tvheadend/tvheadend
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: https://charts.truecharts.org/
    version: 1.2.0
