apiVersion: v2
appVersion: v3.8.1
description: Usenet meta search
name: nzbhydra
version: 1.2.0
upstream_version: 5.3.1
keywords:
  - nzbhydra
  - usenet
home: https://github.com/truecharts/truecharts/tree/master/charts/nzbhydra
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/hydra-icon.png
sources:
  - https://hub.docker.com/r/linuxserver/nzbhydra2
  - https://github.com/theotherp/nzbhydra2
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: https://charts.truecharts.org/
    version: 1.2.0
    
