apiVersion: v2
appversion: 0.2.0.351
description: A fork of Radarr to work with Books & AudioBooks
name: readarr
version: 1.2.0
upstream_version: 1.1.1
keywords:
  - readarr
  - torrent
  - usenet
  - AudioBooks
  - ebooks
home: https://github.com/truecharts/truecharts/tree/master/charts/readarr
icon: https://github.com/Readarr/Readarr/blob/develop/Logo/1024.png?raw=true
sources:
  - https://github.com/Readarr/Readarr
  - https://readarr.com
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: https://charts.truecharts.org/
    version: 1.2.0
    
