apiVersion: v2
appVersion: 3.1.0
description: Free and easy binary newsreader
name: sabnzbd
version: 1.2.0
upstream_version: 4.2.1
keywords:
  - sabnzbd
  - usenet
home: https://github.com/truecharts/truecharts/tree/master/charts/sabnzbd
icon: https://avatars1.githubusercontent.com/u/960698?s=400&v=4
sources:
  - https://hub.docker.com/r/linuxserver/sabnzbd/
  - https://sabnzbd.org/
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: https://charts.truecharts.org/
    version: 1.2.0
    
