apiVersion: v2
appVersion: latest
description: HTPC/Homelab Services Organizer
name: organizr
version: 1.2.0
upstream_version: 3.2.1
keywords:
  - organizr
keywords:
  - heimdall
home: https://github.com/truecharts/charts/tree/dev/charts/organizr
icon: https://github.com/causefx/Organizr/blob/v2-master/plugins/images/organizr/logo.png?raw=true
sources:
  - https://github.com/k8s-at-home/charts/blob/master/charts/organizr/
  - https://github.com/causefx/Organizr
  - https://hub.docker.com/r/organizr/organizr
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: https://charts.truecharts.org/
    version: 1.2.0
