apiVersion: v2
appVersion: 3.0.0.3989
description: A fork of Sonarr to work with movies à la Couchpotato
name: radarr
version: 1.2.0
keywords:
  - radarr
  - torrent
  - usenet
home: https://github.com/truecharts/charts/tree/dev/charts/radarr
icon: https://nzbusenet.com/wp-content/uploads/2017/10/radarr-logo.png
sources:
  - https://github.com/Radarr/Radarr
  - https://hub.docker.com/r/linuxserver/radarr
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: https://charts.truecharts.org/
    version: 1.2.0
