apiVersion: v2
appVersion: 2021.2.2
description: Home Assistant
name: home-assistant
version: 1.2.0
upstream_version: 5.3.0
keywords:
- home-assistant
- hass
- homeassistant
home: https://github.com/truecharts/charts/tree/dev/charts/home-assistant
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Home_Assistant_Logo.svg/519px-Home_Assistant_Logo.svg.png
sources:
- https://github.com/home-assistant/home-assistant
- https://github.com/cdr/code-server
- https://github.com/k8s-at-home/charts/tree/master/charts/home-assistant
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: https://charts.truecharts.org/
    version: 1.2.0

#- name: postgresql
#  version: 10.2.0
#  repository: https://charts.bitnami.com/bitnami
#  condition: postgresql.enabled
## mariadb is currently not ported to SCALE yet.
#  - name: mariadb
#    version: 0.1.0
#    repository: file://../../mariadb/0.0.1/
#    condition: mariadb.enabled
## InfluxDB is currently not ported to SCALE yet.
#- name: influxdb
#  version: 1.1.6
#  repository: https://charts.bitnami.com/bitnami
#  condition: influxdb.enabled
