apiVersion: v2
appVersion: latest
description: Gaps searches through your Plex Server or local folders for all movies, then queries for known movies in the same collection.
name: gaps
version: 1.2.0
upstream_version: 1.1.1
keywords:
  - plex
  - plex-media-server
home: https://github.com/truecharts/truecharts/tree/master/charts/gaps
icon: https://raw.githubusercontent.com/JasonHHouse/gaps/master/images/Final-Black.png
sources:
  - https://github.com/JasonHHouse/gaps
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: https://charts.truecharts.org/
    version: 1.2.0
    
