apiVersion: v2
appVersion: 1.2.5
description: Node-RED is low-code programming for event-driven applications
name: node-red
version: 1.2.0
upstream_version: 5.2.1
keywords:
  - nodered
  - node-red
home: https://github.com/truecharts/charts/tree/dev/charts/node-red
icon: https://nodered.org/about/resources/media/node-red-icon-2.png
sources:
  - https://github.com/node-red/node-red-docker
  - https://github.com/k8s-at-home/charts/tree/master/charts/node-red
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: https://charts.truecharts.org/
    version: 1.2.0
