apiVersion: v2
appVersion: v0.9.0.5
description: Bazarr is a companion application to Bazarr and Radarr. It manages and downloads subtitles based on your requirements
name: bazarr
version: 1.2.0
upstream_version: 5.2.1
keywords:
  - bazarr
  - radarr
  - bazarr
  - subtitles
  - usenet
  - torrent
home: https://github.com/truecharts/charts/tree/dev/charts/bazarr
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/bazarr.png
sources:
  - https://github.com/Bazarr/Bazarr
  - https://hub.docker.com/r/linuxserver/bazarr
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: https://charts.truecharts.org/
    version: 1.2.0
