apiVersion: v2
name: lazylibrarian
description: A Helm chart for deploying LazyLibrarian
version: 1.2.0
appVersion: 1.7.2
upstream_version: 2.1.0
keywords:
  - lazylibrarian
  - ebooks
home: https://github.com/truecharts/truecharts/charts/0.0.1/lazylibrarian
icon: https://lazylibrarian.gitlab.io/logo.svg
sources:
  - https://gitlab.com/LazyLibrarian/LazyLibrarian.git
  - https://lazylibrarian.gitlab.io
maintainers:
  - name: TrueCharts
dependencies:
  - name: common
    repository: https://charts.truecharts.org/
    version: 1.2.0
