# Default values for Unifi.

image:
  repository: jacobalberty/unifi
  tag: stable-6
  pullPolicy: IfNotPresent

strategy:
  type: Recreate

service:
  port:
    port: 8443

env: {}
  # TZ:
  # PUID:
  # PGID:

persistence:
  config:
    enabled: false
    emptyDir: false

appIngressEnabled: false

appAdditionalServicesEnabled: true
appAdditionalServices:
  tcp:
    enabled: true
    type: ClusterIP
    port:
      port: 8080
      name: unificom
      protocol: TCP
      targetPort: 8080
  udp:
    enabled: true
    type: ClusterIP
    port:
      port: 3478
      name: unifistun
      protocol: UDP
      targetPort: 3478

appVolumeMounts:
  config:
    enabled: true
    emptyDir: true
    setPermissions: true
    mountPath: "/unifi"
