apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 0.4.1
upstream_version: 9.14.2
appVersion: 2.4.2
keywords:
  - traefik
  - ingress
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik
  - https://github.com/traefik/traefik-helm-chart
maintainers:
  - name: truecharts
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
dependencies:
  - name: cert-manager
    repository:  "https://charts.jetstack.io"
    version: v1.2.0
  - name: reflector
    repository:  "https://emberstack.github.io/helm-charts"
    version: 5.4.17

