apiVersion: v2
appVersion: 1.15.3
version: 1.2.0
upstream_version: 4.3.1

name: esphome
description: ESPHome is a system to control your ESP8266/ESP32 by simple yet powerful configuration files and control them remotely through Home Automation systems.
home: https://github.com/truecharts/charts/tree/dev/charts/esphome
icon: https://esphome.io/_images/logo.svg
type: application

maintainers:
  - name: TrueCharts

keywords:
  - esphome

sources:
  - https://github.com/esphome/esphome
  - https://hub.docker.com/u/esphome
  - https://github.com/k8s-at-home/charts/tree/master/charts/esphome

dependencies:
  - name: common
    repository: https://charts.truecharts.org/
    version: 1.2.0
